In [47]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update the path if needed
df = pd.read_excel(file_path)

# Convert 'created_at' to datetime format
df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")

# Format the date as "DD/MM/YYYY"
df["date"] = df["created_at"].dt.strftime("%d/%m/%Y")  # This ensures grouping by DD/MM/YYYY format

# Filter transactions with amount > 10
df_filtered = df[df["amount"] > 10]

# Group by formatted date and status, then sum the amounts
summary_final = df_filtered.groupby(["date", "status"])["amount"].sum().unstack(fill_value=0)

# Add overall totals
summary_final.loc["Overall Total"] = summary_final.sum()

# Generate a text-based summary
text_summary_corrected = "Daily Transaction Summary (Amount > ₹10):\n\n"
for date, row in summary_final.iterrows():
    if date != "Overall Total":
        text_summary_corrected += f"{date}: Captured ₹{row.get('captured', 0):,.2f}, Failed ₹{row.get('failed', 0):,.2f}\n"

# Add overall total
text_summary_corrected += f"\nOverall Total: Captured ₹{summary_final.loc['Overall Total', 'captured']:,.2f}, "
text_summary_corrected += f"Failed ₹{summary_final.loc['Overall Total', 'failed']:,.2f}"

# Print the summary
print(text_summary_corrected)

Daily Transaction Summary (Amount > ₹10):

02/03/2025: Captured ₹799.00, Failed ₹0.00
02/05/2025: Captured ₹0.00, Failed ₹499.00
02/07/2025: Captured ₹0.00, Failed ₹998.00
02/08/2025: Captured ₹499.00, Failed ₹0.00
02/09/2025: Captured ₹0.00, Failed ₹1,697.00
02/10/2025: Captured ₹0.00, Failed ₹1,198.00
02/11/2025: Captured ₹499.00, Failed ₹998.00
02/12/2025: Captured ₹1,897.00, Failed ₹1,697.00
03/01/2025: Captured ₹14,471.00, Failed ₹6,487.00
03/02/2025: Captured ₹2,495.00, Failed ₹998.00

Overall Total: Captured ₹20,660.00, Failed ₹14,572.00

In [55]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Display the first few rows to check column names and data structure
print(df.head())

# Display column names
print("\nColumn Names:", df.columns.tolist())

                   id  amount currency    status              order_id  \
0  pay_PqJB0fhEfvVIq1     1.0      INR  captured  order_PqJA27hLbYkcN9
1  pay_PqLnXZgva35MX8     1.0      INR  captured  order_PqLnO5NvGQtRoy
2  pay_PqNt6FFcV6w1zj     1.0      INR  captured  order_PqNsyFOJhGiffC
3  pay_PqOemwxpjbxFOo     1.0      INR  captured  order_PqOeiLLdwtOkYH
4  pay_PqQlv6exiHizgy     1.0      INR  captured  order_PqQlmsfyK6shgo

   invoice_id  international  method  amount_refunded  amount_transferred  \
0         NaN              0  wallet              0.0                   0
1         NaN              0  wallet              0.0                   0
2         NaN              0  wallet              0.0                   0
3         NaN              0  wallet              0.0                   0
4         NaN              0  wallet              0.0                   0

   ...  tax  error_code error_description           created_at card_type  \
0  ...  0.0         NaN               NaN  01/02/2025 09:36:25       NaN
1  ...  0.0         NaN               NaN  01/02/2025 12:10:17       NaN
2  ...  0.0         NaN               NaN  01/02/2025 14:12:56       NaN
3  ...  0.0         NaN               NaN  01/02/2025 14:58:05       NaN
4  ...  0.0         NaN               NaN  01/02/2025 17:02:13       NaN

  card_network Auth_code             Payments_ARN Payments_RRN  flow
0          NaN       NaN  T2502010936361180842023          NaN   NaN
1          NaN       NaN  T2502011210442096194380          NaN   NaN
2          NaN       NaN  T2502011413170985540231          NaN   NaN
3          NaN       NaN  T2502011458268022711419          NaN   NaN
4          NaN       NaN  T2502011702206360519254          NaN   NaN

[5 rows x 32 columns]

Column Names: ['id', 'amount', 'currency', 'status', 'order_id', 'invoice_id', 'international', 'method', 'amount_refunded', 'amount_transferred', 'refund_status', 'captured', 'description', 'card_id', 'card', 'bank', 'wallet', 'vpa', 'email', 'contact', 'notes', 'fee', 'tax', 'error_code', 'error_description', 'created_at', 'card_type', 'card_network', 'Auth_code', 'Payments_ARN', 'Payments_RRN', 'flow']

In [59]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Pivot table to sum amounts based on status ('captured' or 'failed')
daily_totals = df.pivot_table(
    index='date', 
    columns='status', 
    values='amount', 
    aggfunc='sum', 
    fill_value=0
).reset_index()

# Print column names to debug
print("Columns in daily_totals:", daily_totals.columns.tolist())

# Rename columns dynamically to ensure no mismatches
new_column_names = ['Date'] + list(daily_totals.columns[1:])  # Keeping status names as they are
daily_totals.columns = new_column_names

# Calculate overall totals
overall_totals = daily_totals.iloc[:, 1:].sum()  # Sum all columns except 'Date'

# Display results
print("Daily Totals:")
print(daily_totals)
print("\nOverall Totals:")
print(overall_totals)

# Save results to an Excel file
output_file = "daily_totals.xlsx"
daily_totals.to_excel(output_file, index=False)
print(f"\nResults saved to {output_file}")

Columns in daily_totals: ['date', 'captured', 'failed', 'refunded']
Daily Totals:
          Date  captured   failed  refunded
0   2025-02-01       8.0      1.0       0.0
1   2025-02-02       7.0      1.0       0.0
2   2025-02-03     802.0      0.0       0.0
3   2025-02-04       3.0      0.0       0.0
4   2025-02-05       1.0    499.0       0.0
5   2025-02-07       0.0    998.0       0.0
6   2025-02-08     508.0      1.0       0.0
7   2025-02-09       0.0   1697.0       0.0
8   2025-02-10       0.0   1198.0       0.0
9   2025-02-11     499.0    998.0       0.0
10  2025-02-12    1897.0   1697.0       0.0
11  2025-02-13     998.0   2097.0       0.0
12  2025-02-14    9731.3   2695.0       0.0
13  2025-02-15     699.0      0.0       0.0
14  2025-02-16     998.0    998.0       0.0
15  2025-02-17    5590.0      0.0       0.0
16  2025-02-18    8184.0   2495.0       0.0
17  2025-02-19   15469.0  16467.0       0.0
18  2025-02-20   33186.3   8085.0       0.0
19  2025-02-21   19461.0   4491.0       0.0
20  2025-02-22   21158.0   9481.0       0.0
21  2025-02-23   16667.0   3992.0       0.0
22  2025-02-24   19960.0   3493.0       0.0
23  2025-02-25   12475.0   5988.0       0.0
24  2025-02-26   11877.0   4491.0       0.0
25  2025-02-27   11178.0   5988.0    4491.0
26  2025-02-28   27445.0   9481.0       0.0
27  2025-03-01   14471.0   6487.0       0.0
28  2025-03-02    2495.0    998.0       0.0
29  2025-03-21       1.0      0.0       0.0
30  2025-03-22       1.0      0.0       0.0
31  2025-03-25       0.0    499.0       0.0

Overall Totals:
captured    235769.6
failed       95316.0
refunded      4491.0
dtype: float64

Results saved to daily_totals.xlsx

In [63]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Pivot table to sum amounts based on status ('captured' or 'failed')
daily_totals = df.pivot_table(
    index='date', 
    columns='status', 
    values='amount', 
    aggfunc='sum', 
    fill_value=0
).reset_index()

# Rename columns dynamically to ensure no mismatches
new_column_names = ['Date'] + list(daily_totals.columns[1:])  # Keeping status names as they are
daily_totals.columns = new_column_names

# Save results to an Excel file
output_file = "daily_totals.xlsx"
daily_totals.to_excel(output_file, index=False)

output_file

'daily_totals.xlsx'

In [71]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Filter only relevant statuses
df = df[df['status'].isin(['captured', 'failed'])]

# Pivot table to sum amounts based on status
daily_totals = df.pivot_table(
    index='date', 
    columns='status', 
    values='amount', 
    aggfunc='sum', 
    fill_value=0
).reset_index()

# Rename columns for clarity
daily_totals.columns = ['Date', 'Captured', 'Failed']

# Filter days where either Captured or Failed amount is greater than 10
daily_totals_filtered = daily_totals[(daily_totals['Captured'] > 10) | (daily_totals['Failed'] > 10)]

# Print and save results
print(daily_totals_filtered)

# Save results to an Excel file
output_file = "daily_totals_filtered.xlsx"
daily_totals_filtered.to_excel(output_file, index=False)

print(f"Results saved to {output_file}")
# Filter only relevant statuses (captured, failed) to prevent extra columns
df_filtered = df[df['status'].isin(['captured', 'failed'])]

# Group by date and status to count occurrences and sum amounts
daily_counts = df_filtered.groupby(['date', 'status']).agg(
    count=('amount', 'count'), 
    total_amount=('amount', 'sum')
).unstack(fill_value=0).reset_index()

# Flatten column names
daily_counts.columns = ['Date', 'Captured_Count', 'Failed_Count', 'Captured_Amount', 'Failed_Amount']

# Filter rows where either Captured_Amount or Failed_Amount is greater than 10
daily_counts_filtered = daily_counts[(daily_counts['Captured_Amount'] > 10) | (daily_counts['Failed_Amount'] > 10)]

# Display results
daily_counts_filtered

          Date  Captured   Failed
2   2025-02-03     802.0      0.0
4   2025-02-05       1.0    499.0
5   2025-02-07       0.0    998.0
6   2025-02-08     508.0      1.0
7   2025-02-09       0.0   1697.0
8   2025-02-10       0.0   1198.0
9   2025-02-11     499.0    998.0
10  2025-02-12    1897.0   1697.0
11  2025-02-13     998.0   2097.0
12  2025-02-14    9731.3   2695.0
13  2025-02-15     699.0      0.0
14  2025-02-16     998.0    998.0
15  2025-02-17    5590.0      0.0
16  2025-02-18    8184.0   2495.0
17  2025-02-19   15469.0  16467.0
18  2025-02-20   33186.3   8085.0
19  2025-02-21   19461.0   4491.0
20  2025-02-22   21158.0   9481.0
21  2025-02-23   16667.0   3992.0
22  2025-02-24   19960.0   3493.0
23  2025-02-25   12475.0   5988.0
24  2025-02-26   11877.0   4491.0
25  2025-02-27   11178.0   5988.0
26  2025-02-28   27445.0   9481.0
27  2025-03-01   14471.0   6487.0
28  2025-03-02    2495.0    998.0
31  2025-03-25       0.0    499.0
Results saved to daily_totals_filtered.xlsx

          Date  Captured_Count  Failed_Count  Captured_Amount  Failed_Amount
2   2025-02-03               4             0            802.0            0.0
4   2025-02-05               1             1              1.0          499.0
5   2025-02-07               0             2              0.0          998.0
6   2025-02-08              10             1            508.0            1.0
7   2025-02-09               0             3              0.0         1697.0
8   2025-02-10               0             2              0.0         1198.0
9   2025-02-11               1             2            499.0          998.0
10  2025-02-12               3             3           1897.0         1697.0
11  2025-02-13               1             3            998.0         2097.0
12  2025-02-14               8             5           9731.3         2695.0
13  2025-02-15               1             0            699.0            0.0
14  2025-02-16               2             2            998.0          998.0
15  2025-02-17               7             0           5590.0            0.0
16  2025-02-18               7             5           8184.0         2495.0
17  2025-02-19              21            30          15469.0        16467.0
18  2025-02-20              22            14          33186.3         8085.0
19  2025-02-21              19             8          19461.0         4491.0
20  2025-02-22              27            16          21158.0         9481.0
21  2025-02-23              20             8          16667.0         3992.0
22  2025-02-24              26             5          19960.0         3493.0
23  2025-02-25              22            10          12475.0         5988.0
24  2025-02-26              18             9          11877.0         4491.0
25  2025-02-27              16            10          11178.0         5988.0
26  2025-02-28              26             9          27445.0         9481.0
27  2025-03-01              26            12          14471.0         6487.0
28  2025-03-02               4             2           2495.0          998.0
31  2025-03-25               0             1              0.0          499.0

In [73]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Filter only relevant statuses
df = df[df['status'].isin(['captured', 'failed'])]

# Group by date and status to get the count and sum of amounts
daily_counts = df.groupby(['date', 'status']).agg(
    count=('amount', 'count'), 
    total_amount=('amount', 'sum')
).unstack(fill_value=0).reset_index()

# Flatten column names
daily_counts.columns = ['Date', 'Captured_Count', 'Failed_Count', 'Captured_Amount', 'Failed_Amount']

# Calculate the real captured amount (Count * Amount per day)
daily_counts['Captured_Real'] = daily_counts['Captured_Count'] * daily_counts['Captured_Amount']

# Filter rows where either Captured_Amount or Failed_Amount is greater than 10
daily_counts_filtered = daily_counts[(daily_counts['Captured_Amount'] > 10) | (daily_counts['Failed_Amount'] > 10)]

# Print and save results
print(daily_counts_filtered)

# Save results to an Excel file
output_file = "daily_totals_filtered.xlsx"
daily_counts_filtered.to_excel(output_file, index=False)

print(f"Results saved to {output_file}")

          Date  Captured_Count  Failed_Count  Captured_Amount  Failed_Amount  \
2   2025-02-03               4             0            802.0            0.0
4   2025-02-05               1             1              1.0          499.0
5   2025-02-07               0             2              0.0          998.0
6   2025-02-08              10             1            508.0            1.0
7   2025-02-09               0             3              0.0         1697.0
8   2025-02-10               0             2              0.0         1198.0
9   2025-02-11               1             2            499.0          998.0
10  2025-02-12               3             3           1897.0         1697.0
11  2025-02-13               1             3            998.0         2097.0
12  2025-02-14               8             5           9731.3         2695.0
13  2025-02-15               1             0            699.0            0.0
14  2025-02-16               2             2            998.0          998.0
15  2025-02-17               7             0           5590.0            0.0
16  2025-02-18               7             5           8184.0         2495.0
17  2025-02-19              21            30          15469.0        16467.0
18  2025-02-20              22            14          33186.3         8085.0
19  2025-02-21              19             8          19461.0         4491.0
20  2025-02-22              27            16          21158.0         9481.0
21  2025-02-23              20             8          16667.0         3992.0
22  2025-02-24              26             5          19960.0         3493.0
23  2025-02-25              22            10          12475.0         5988.0
24  2025-02-26              18             9          11877.0         4491.0
25  2025-02-27              16            10          11178.0         5988.0
26  2025-02-28              26             9          27445.0         9481.0
27  2025-03-01              26            12          14471.0         6487.0
28  2025-03-02               4             2           2495.0          998.0
31  2025-03-25               0             1              0.0          499.0

    Captured_Real
2          3208.0
4             1.0
5             0.0
6          5080.0
7             0.0
8             0.0
9           499.0
10         5691.0
11          998.0
12        77850.4
13          699.0
14         1996.0
15        39130.0
16        57288.0
17       324849.0
18       730098.6
19       369759.0
20       571266.0
21       333340.0
22       518960.0
23       274450.0
24       213786.0
25       178848.0
26       713570.0
27       376246.0
28         9980.0
31            0.0
Results saved to daily_totals_filtered.xlsx

In [75]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Filter transactions where amount > 10
df_filtered = df[(df['status'].isin(['captured', 'failed'])) & (df['amount'] > 10)]

# Group by date and status to count and sum amounts for transactions > 10
daily_counts = df_filtered.groupby(['date', 'status']).agg(
    Transaction_Count=('amount', 'count'),  # Count transactions with amount > 10
    Total_Amount=('amount', 'sum')  # Sum only amounts > 10
).unstack(fill_value=0).reset_index()

# Flatten column names
daily_counts.columns = ['Date', 'Captured_Count', 'Failed_Count', 'Captured_Amount', 'Failed_Amount']

# Save results to an Excel file
output_file = "daily_totals_filtered.xlsx"
daily_counts.to_excel(output_file, index=False)

# Print final result
print(daily_counts)
print(f"Results saved to {output_file}")

          Date  Captured_Count  Failed_Count  Captured_Amount  Failed_Amount
0   2025-02-03               1             0            799.0            0.0
1   2025-02-05               0             1              0.0          499.0
2   2025-02-07               0             2              0.0          998.0
3   2025-02-08               1             0            499.0            0.0
4   2025-02-09               0             3              0.0         1697.0
5   2025-02-10               0             2              0.0         1198.0
6   2025-02-11               1             2            499.0          998.0
7   2025-02-12               3             3           1897.0         1697.0
8   2025-02-13               1             3            998.0         2097.0
9   2025-02-14               8             5           9731.3         2695.0
10  2025-02-15               1             0            699.0            0.0
11  2025-02-16               2             2            998.0          998.0
12  2025-02-17               7             0           5590.0            0.0
13  2025-02-18               7             5           8184.0         2495.0
14  2025-02-19              21            30          15469.0        16467.0
15  2025-02-20              22            14          33186.3         8085.0
16  2025-02-21              19             8          19461.0         4491.0
17  2025-02-22              27            16          21158.0         9481.0
18  2025-02-23              20             8          16667.0         3992.0
19  2025-02-24              26             5          19960.0         3493.0
20  2025-02-25              22            10          12475.0         5988.0
21  2025-02-26              18             9          11877.0         4491.0
22  2025-02-27              16            10          11178.0         5988.0
23  2025-02-28              26             9          27445.0         9481.0
24  2025-03-01              26            12          14471.0         6487.0
25  2025-03-02               4             2           2495.0          998.0
26  2025-03-25               0             1              0.0          499.0
Results saved to daily_totals_filtered.xlsx

In [77]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' column is numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Filter transactions where amount > 10
df_filtered = df[(df['status'].isin(['captured', 'failed'])) & (df['amount'] > 10)]

# Group by date and status to count and sum amounts for transactions > 10
daily_counts = df_filtered.groupby(['date', 'status']).agg(
    Transaction_Count=('amount', 'count'),  # Count transactions with amount > 10
    Total_Amount=('amount', 'sum')  # Sum only amounts > 10
).unstack(fill_value=0).reset_index()

# Flatten column names
daily_counts.columns = ['Date', 'Captured_Count', 'Failed_Count', 'Captured_Amount', 'Failed_Amount']

# Calculate total captured and total failed
total_captured_count = daily_counts['Captured_Count'].sum()
total_captured_amount = daily_counts['Captured_Amount'].sum()
total_failed_count = daily_counts['Failed_Count'].sum()
total_failed_amount = daily_counts['Failed_Amount'].sum()

# Add total row at the end
total_row = pd.DataFrame({
    'Date': ['Total'],
    'Captured_Count': [total_captured_count],
    'Captured_Amount': [total_captured_amount],
    'Failed_Count': [total_failed_count],
    'Failed_Amount': [total_failed_amount]
})

# Append total row to the dataframe
daily_counts = pd.concat([daily_counts, total_row], ignore_index=True)

# Save results to an Excel file
output_file = "daily_totals_filtered.xlsx"
daily_counts.to_excel(output_file, index=False)

# Print final result
print(daily_counts)
print(f"Results saved to {output_file}")

          Date  Captured_Count  Failed_Count  Captured_Amount  Failed_Amount
0   2025-02-03               1             0            799.0            0.0
1   2025-02-05               0             1              0.0          499.0
2   2025-02-07               0             2              0.0          998.0
3   2025-02-08               1             0            499.0            0.0
4   2025-02-09               0             3              0.0         1697.0
5   2025-02-10               0             2              0.0         1198.0
6   2025-02-11               1             2            499.0          998.0
7   2025-02-12               3             3           1897.0         1697.0
8   2025-02-13               1             3            998.0         2097.0
9   2025-02-14               8             5           9731.3         2695.0
10  2025-02-15               1             0            699.0            0.0
11  2025-02-16               2             2            998.0          998.0
12  2025-02-17               7             0           5590.0            0.0
13  2025-02-18               7             5           8184.0         2495.0
14  2025-02-19              21            30          15469.0        16467.0
15  2025-02-20              22            14          33186.3         8085.0
16  2025-02-21              19             8          19461.0         4491.0
17  2025-02-22              27            16          21158.0         9481.0
18  2025-02-23              20             8          16667.0         3992.0
19  2025-02-24              26             5          19960.0         3493.0
20  2025-02-25              22            10          12475.0         5988.0
21  2025-02-26              18             9          11877.0         4491.0
22  2025-02-27              16            10          11178.0         5988.0
23  2025-02-28              26             9          27445.0         9481.0
24  2025-03-01              26            12          14471.0         6487.0
25  2025-03-02               4             2           2495.0          998.0
26  2025-03-25               0             1              0.0          499.0
27       Total             279           162         235736.6        95313.0
Results saved to daily_totals_filtered.xlsx

In [7]:
import pandas as pd

# Load the Excel file
file_path = "techfest25.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Convert 'created_at' column to datetime format
df['created_at'] = pd.to_datetime(df['created_at'], format='%d/%m/%Y %H:%M:%S')

# Extract only the date part (ignoring time)
df['date'] = df['created_at'].dt.date

# Ensure 'amount' and 'taxfee' columns are numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['taxfee'] = pd.to_numeric(df['fee'], errors='coerce')  # Fix column name

# Filter transactions where amount > 10
df_filtered = df[(df['status'].isin(['captured', 'failed'])) & (df['amount'] > 10)]

# Group by date and status to count and sum amounts for transactions > 10
daily_counts = df_filtered.groupby(['date', 'status']).agg(
    Transaction_Count=('amount', 'count'),
    Total_Amount=('amount', 'sum'),
    Total_Taxfee=('taxfee', 'sum')  # Fix column reference
).unstack(fill_value=0).reset_index()

# Flatten column names
daily_counts.columns = [
    'Date', 'Captured_Count', 'Failed_Count', 
    'Captured_Amount', 'Failed_Amount', 
    'Captured_Taxfee', 'Failed_Taxfee'
]

# Calculate net captured amount (Captured_Amount - Captured_Taxfee)
daily_counts['Captured_Net_Amount'] = daily_counts['Captured_Amount'] - daily_counts['Captured_Taxfee']

# Calculate totals for all columns
total_captured_count = daily_counts['Captured_Count'].sum()
total_captured_amount = daily_counts['Captured_Amount'].sum()
total_captured_net_amount = daily_counts['Captured_Net_Amount'].sum()
total_captured_taxfee = daily_counts['Captured_Taxfee'].sum()
total_failed_count = daily_counts['Failed_Count'].sum()
total_failed_amount = daily_counts['Failed_Amount'].sum()
total_failed_taxfee = daily_counts['Failed_Taxfee'].sum()

# Add total row at the end
total_row = pd.DataFrame({
    'Date': ['Total'],
    'Captured_Count': [total_captured_count],
    'Captured_Amount': [total_captured_amount],
    'Captured_Taxfee': [total_captured_taxfee],
    'Captured_Net_Amount': [total_captured_net_amount],
    'Failed_Count': [total_failed_count],
    'Failed_Amount': [total_failed_amount],
    'Failed_Taxfee': [total_failed_taxfee]
})

# Append total row to the dataframe
daily_counts = pd.concat([daily_counts, total_row], ignore_index=True)

# Save results to an Excel file
output_file = "daily_totals_filtered.xlsx"
daily_counts.to_excel(output_file, index=False)

# Print final result
print(daily_counts)
print(f"Results saved to {output_file}")

          Date  Captured_Count  Failed_Count  Captured_Amount  Failed_Amount  \
0   2025-02-03               1             0            799.0            0.0
1   2025-02-05               0             1              0.0          499.0
2   2025-02-07               0             2              0.0          998.0
3   2025-02-08               1             0            499.0            0.0
4   2025-02-09               0             3              0.0         1697.0
5   2025-02-10               0             2              0.0         1198.0
6   2025-02-11               1             2            499.0          998.0
7   2025-02-12               3             3           1897.0         1697.0
8   2025-02-13               1             3            998.0         2097.0
9   2025-02-14               8             5           9731.3         2695.0
10  2025-02-15               1             0            699.0            0.0
11  2025-02-16               2             2            998.0          998.0
12  2025-02-17               7             0           5590.0            0.0
13  2025-02-18               7             5           8184.0         2495.0
14  2025-02-19              21            30          15469.0        16467.0
15  2025-02-20              22            14          33186.3         8085.0
16  2025-02-21              19             8          19461.0         4491.0
17  2025-02-22              27            16          21158.0         9481.0
18  2025-02-23              20             8          16667.0         3992.0
19  2025-02-24              26             5          19960.0         3493.0
20  2025-02-25              22            10          12475.0         5988.0
21  2025-02-26              18             9          11877.0         4491.0
22  2025-02-27              16            10          11178.0         5988.0
23  2025-02-28              26             9          27445.0         9481.0
24  2025-03-01              26            12          14471.0         6487.0
25  2025-03-02               4             2           2495.0          998.0
26  2025-03-25               0             1              0.0          499.0
27       Total             279           162         235736.6        95313.0

    Captured_Taxfee  Failed_Taxfee  Captured_Net_Amount
0             18.86            0.0               780.14
1              0.00            0.0                 0.00
2              0.00            0.0                 0.00
3              9.98            0.0               489.02
4              0.00            0.0                 0.00
5              0.00            0.0                 0.00
6             11.78            0.0               487.22
7             44.78            0.0              1852.22
8             23.56            0.0               974.44
9            229.69            0.0              9501.61
10            16.50            0.0               682.50
11            23.56            0.0               974.44
12           131.96            0.0              5458.04
13           191.36            0.0              7992.64
14           365.14            0.0             15103.86
15           779.66            0.0             32406.64
16           453.90            0.0             19007.10
17           499.42            0.0             20658.58
18           391.60            0.0             16275.40
19           467.54            0.0             19492.46
20           290.90            0.0             12184.10
21           278.56            0.0             11598.44
22           263.86            0.0             10914.14
23           647.78            0.0             26797.22
24           341.62            0.0             14129.38
25            58.90            0.0              2436.10
26             0.00            0.0                 0.00
27          5540.91            0.0            230195.69
Results saved to daily_totals_filtered.xlsx